CREATE TABLE BOARD 
(
  BOARD_TYPE VARCHAR2(5 BYTE) NOT NULL 
, BOARD_NUM NUMBER(4, 0) NOT NULL 
, BOARD_TITLE VARCHAR2(50 BYTE) 
, BOARD_COMMENT VARCHAR2(1000 BYTE) 
, CREATOR VARCHAR2(15 BYTE) 
, CREATE_TIME VARCHAR2(14 BYTE) 
, MODIFIER VARCHAR2(15 BYTE) 
, MODIFIED_TIME VARCHAR2(14 BYTE) 
, FILE_ROOT VARCHAR2(200 BYTE) 
, CONSTRAINT TABLE1_PK PRIMARY KEY 
  (
    BOARD_NUM 
  , BOARD_TYPE 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX BOARD_PK ON BOARD (BOARD_TYPE ASC, BOARD_NUM ASC) 
      LOGGING 
      TABLESPACE USERS 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLEL;

COMMENT ON COLUMN BOARD.BOARD_TYPE IS ' Խñ Ÿ  ';

COMMENT ON COLUMN BOARD.BOARD_NUM IS ' Խñ    ȣ';

COMMENT ON COLUMN BOARD.BOARD_TITLE IS ' Խñ      ';

COMMENT ON COLUMN BOARD.BOARD_COMMENT IS ' Խñ      ';

COMMENT ON COLUMN BOARD.CREATOR IS '      ';

COMMENT ON COLUMN BOARD.CREATE_TIME IS '     ð ';

COMMENT ON COLUMN BOARD.MODIFIER IS '      ';

COMMENT ON COLUMN BOARD.MODIFIED_TIME IS '     ð ';

COMMENT ON COLUMN BOARD.FILE_ROOT IS '    ';


CREATE TABLE COM_CODE 
(
  CODE_TYPE VARCHAR2(10 BYTE) NOT NULL 
, CODE_ID VARCHAR2(10 BYTE) NOT NULL 
, CODE_NAME VARCHAR2(20 BYTE) 
, CREATOR VARCHAR2(8 BYTE) 
, CREATE_TIME VARCHAR2(14 BYTE) 
, MODIFIER VARCHAR2(8 BYTE) 
, MODIFIED_TIME VARCHAR2(14 BYTE) 
, CONSTRAINT COM_CODE_PK PRIMARY KEY 
  (
    CODE_TYPE 
  , CODE_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX COM_CODE_PK ON COM_CODE (CODE_TYPE ASC, CODE_ID ASC) 
      LOGGING 
      TABLESPACE USERS 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLEL;

CREATE TABLE USER_INFO 
(
  USER_ID VARCHAR2(15 BYTE) NOT NULL 
, USER_PW VARCHAR2(16 BYTE) 
, USER_NAME VARCHAR2(15 BYTE) 
, USER_PHONE1 VARCHAR2(3 BYTE) 
, USER_PHONE2 VARCHAR2(4 BYTE) 
, USER_PHONE3 VARCHAR2(4 BYTE) 
, USER_ADDR1 VARCHAR2(8 BYTE) 
, USER_ADDR2 VARCHAR2(150 BYTE) 
, USER_COMPANY VARCHAR2(60 BYTE) 
, CREATOR VARCHAR2(15 BYTE) 
, CREATE_TIME VARCHAR2(14 BYTE) 
, MODIFIER VARCHAR2(15 BYTE) 
, MODIFIED_TIME VARCHAR2(14 BYTE) 
, CONSTRAINT USER_PK PRIMARY KEY 
  (
    USER_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX USER_PK ON USER_INFO (USER_ID ASC) 
      LOGGING 
      TABLESPACE USERS 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLEL;


  INSERT INTO 
        BOARD
        (BOARD_TYPE
        ,BOARD_NUM
        ,BOARD_TITLE
        ,BOARD_COMMENT
        ,CREATOR
        ,CREATE_TIME
        ,MODIFIER
        ,MODIFIED_TIME
        )
        VALUES
        ('1'
        ,1
        ,'왜안되누'
        ,'뭐가문제구'
        ,'SYSTEM'
        ,TO_CHAR(SYSDATE)
        ,'SYSTEM'
        ,TO_CHAR(SYSDATE)
        );
        
        
        select * from board;


