
-- MBTI 계정 만들기

DROP TABLE TB_MBTI;
DROP SEQUENCE SEQ_MBTI;

CREATE TABLE TB_MBTI(

MBTI_NUM NUMBER PRIMARY KEY
, MBTI_TWOTYPE VARCHAR2(2 BYTE) NOT NULL CHECK ( MBTI_TWOTYPE IN ('EI','NS','FT','JP')) 
, MBTI_QUIZ VARCHAR2(500 BYTE) NOT NULL
, CREATOR VARCHAR2(15 BYTE) 
, CREATE_TIME VARCHAR2(14 BYTE) 
, MODIFIER VARCHAR2(15 BYTE) 
, MODIFIED_TIME VARCHAR2(14 BYTE) 
, STATE CHAR(1 BYTE) DEFAULT 'Y' CHECK ( STATE IN ('Y','N')) 

)
;

CREATE SEQUENCE SEQ_MBTI
NOCACHE;

INSERT INTO TB_MBTI VALUES (SEQ_MBTI.NEXTVAL, 'EI', '주기적으로 새로운 친구를 만든다.' , 'ADMIN', TO_CHAR(SYSDATE),NULL,NULL,'Y');
INSERT INTO TB_MBTI VALUES (SEQ_MBTI.NEXTVAL, 'EI', '자유 시간 중 상당 부분을 다양한 관심사를 탐구하는 데 할애한다.' , 'ADMIN', TO_CHAR(SYSDATE),NULL,NULL,'Y');
INSERT INTO TB_MBTI VALUES (SEQ_MBTI.NEXTVAL, 'EI', '파티나 행사에서 새로운 사람에게 먼저 자신을 소개하기보다는 주로 이미 알고 있는 사람과 대화하는 편이다.' , 'ADMIN', TO_CHAR(SYSDATE),NULL,NULL,'Y');

INSERT INTO TB_MBTI VALUES (SEQ_MBTI.NEXTVAL, 'NS', '예술 작품의 다양한 해석에 대해 토론하는 일에는 크게 관심이 있다.' , 'ADMIN', TO_CHAR(SYSDATE),NULL,NULL,'Y');
INSERT INTO TB_MBTI VALUES (SEQ_MBTI.NEXTVAL, 'NS', '결말을 자신의 방식으로 해석할 수 있는 책과 영화를 좋아한다.' , 'ADMIN', TO_CHAR(SYSDATE),NULL,NULL,'Y');
INSERT INTO TB_MBTI VALUES (SEQ_MBTI.NEXTVAL, 'NS', '일이 잘못될까봐 자주 걱정하는 편이다.' , 'ADMIN', TO_CHAR(SYSDATE),NULL,NULL,'Y');

INSERT INTO TB_MBTI VALUES (SEQ_MBTI.NEXTVAL, 'FT', '다른 사람이 울고 있는 모습을 보면 자신도 울고 싶어질 때가 많다.' , 'ADMIN', TO_CHAR(SYSDATE),NULL,NULL,'Y');
INSERT INTO TB_MBTI VALUES (SEQ_MBTI.NEXTVAL, 'FT', '매우 감상적인 편이다.' , 'ADMIN', TO_CHAR(SYSDATE),NULL,NULL,'Y');
INSERT INTO TB_MBTI VALUES (SEQ_MBTI.NEXTVAL, 'FT', '작은 실수로도 자신의 능력이나 지식을 의심하곤 한다.' , 'ADMIN', TO_CHAR(SYSDATE),NULL,NULL,'Y');

INSERT INTO TB_MBTI VALUES (SEQ_MBTI.NEXTVAL, 'JP', '일이 잘못될 때를 대비해 여러 대비책을 세우는 편이다.' , 'ADMIN', TO_CHAR(SYSDATE),NULL,NULL,'Y');
INSERT INTO TB_MBTI VALUES (SEQ_MBTI.NEXTVAL, 'JP', '일정이나 목록으로 계획을 세우는 일을 좋아한다.' , 'ADMIN', TO_CHAR(SYSDATE),NULL,NULL,'Y');
INSERT INTO TB_MBTI VALUES (SEQ_MBTI.NEXTVAL, 'JP', '하나의 프로젝트를 완전히 완료한 후 다른 프로젝트를 시작하는 편이다.' , 'ADMIN', TO_CHAR(SYSDATE),NULL,NULL,'Y');

COMMIT;




SELECT MBTI_NUM, MBTI_TWOTYPE, MBTI_QUIZ
FROM TB_MBTI
WHERE STATE = 'Y'
AND MBTI_NUM BETWEEN 1 AND 6 
;