DROP TABLE RECRUIT;

DROP SEQUENCE SEQ_RECRUIT;
DROP SEQUENCE SEQ_Education;
DROP SEQUENCE SEQ_CERTIFICATE;
DROP SEQUENCE SEQ_CAREER;

CREATE TABLE RECRUIT (
	SEQ	VARCHAR(255)		NOT NULL,
	NAME	VARCHAR(255)		NULL,
	BIRTH	VARCHAR(255)		NULL,
	GENDER	VARCHAR(255)		NULL,
	PHONE	VARCHAR(255)		NULL,
	EMAIL	VARCHAR(255)		NULL,
	ADDR	VARCHAR(255)		NULL,
	LOCATION	VARCHAR(255)	NULL,
	WORK_TYPE	VARCHAR(255)	NULL,
	SUBMIT	VARCHAR(255)	NULL
    -- (번호), 이름, 생일, 성별, 연락처, 이메일, 주소, 희망근무지, 근무형태, (이미 등록된 사람인지)
);


CREATE SEQUENCE SEQ_RECRUIT
NOCACHE;

CREATE SEQUENCE SEQ_Education
NOCACHE;

CREATE SEQUENCE SEQ_CERTIFICATE
NOCACHE;

CREATE SEQUENCE SEQ_CAREER
NOCACHE;

DROP TABLE Education;

CREATE TABLE Education (
	EDU_SEQ	VARCHAR(255)		NOT NULL,
	SEQ	VARCHAR(255)		NOT NULL,
	SCHOOL_NAME	VARCHAR(255)		NULL,
	DIVISION	VARCHAR(255)		NULL,
	START_PERIOD	VARCHAR(255)		NULL,
	END_PERIOD	VARCHAR(255)		NULL,
	MAJOR	VARCHAR(255)		NULL,
	GRADE	VARCHAR(255)		NULL,
	LOCATION	VARCHAR(255)	NULL

);

DROP TABLE CERTIFICATE;

CREATE TABLE CERTIFICATE (
	CERT_SEQ	VARCHAR(255)		NOT NULL,
	SEQ	VARCHAR(255)		NOT NULL,
	QUALIFI_NAME	VARCHAR(255)		NULL,
	ACQU_DATE	VARCHAR(255)		NULL,
	ORGANIZE_NAME	VARCHAR(255)		NULL
);

DROP TABLE CAREER;

CREATE TABLE CAREER (
	CAR_SEQ	VARCHAR(255)		NOT NULL,
	SEQ	VARCHAR(255)		NOT NULL,
	COMP_NAME	VARCHAR(255)		NULL,
	LOCATION	VARCHAR(255)		NULL,
	START_PERIOD	VARCHAR(255)		NULL,
	END_PERIOD	VARCHAR(255)		NULL,
	TASK	VARCHAR(255)		NULL,
	SALARY	VARCHAR(255)		NULL
);

-- 회사명,   , 근무기간,  부서/직급/직책,   지역


ALTER TABLE RECRUIT ADD CONSTRAINT PK_RECRUIT PRIMARY KEY (
	SEQ
);

ALTER TABLE Education ADD CONSTRAINT PK_EDUCATION PRIMARY KEY (
	EDU_SEQ,
	SEQ
);

ALTER TABLE CERTIFICATE ADD CONSTRAINT PK_CERTIFICATE PRIMARY KEY (
	CERT_SEQ,
	SEQ
);

ALTER TABLE CAREER ADD CONSTRAINT PK_CAREER PRIMARY KEY (
	CAR_SEQ,
	SEQ
);

ALTER TABLE Education ADD CONSTRAINT FK_RECRUIT_TO_Education_1 FOREIGN KEY (
	SEQ
)
REFERENCES RECRUIT (
	SEQ
);

ALTER TABLE CERTIFICATE ADD CONSTRAINT FK_RECRUIT_TO_CERTIFICATE_1 FOREIGN KEY (
	SEQ
)
REFERENCES RECRUIT (
	SEQ
);

ALTER TABLE CAREER ADD CONSTRAINT FK_RECRUIT_TO_CAREER_1 FOREIGN KEY (
	SEQ
)
REFERENCES RECRUIT (
	SEQ
);

